"""
20_estimate_baseline_model.py
====================
Intra-ETF spillover model with endogenous shock definition.

The shock is the CAR of a constituent stock relative to a SECTOR benchmark
(not the market index), estimated via a rolling OLS market model.
Using a sector benchmark avoids the endogeneity problem of using the ETF
itself as benchmark for its own constituents.

SCOPE: XME and XLE only (validation run).
       Set VALIDATION_MODE = False to run all 5 ETFs.

KEY OPTIMIZATION: identify_shocks() is fully vectorized using numpy matrix
operations instead of a per-date loop. This reduces runtime from hours to
minutes for ETFs with ~30 constituents.

Inputs:
    processed/{etf}_holdings.csv   (from 01_load_holdings.py)
    processed/returns_clean.csv    (from 11_compute_returns.py)

Outputs:
    results/panel_full.csv
    results/regression_results.txt
    results/coef_plot.png
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

# ================================================================================
# CONFIGURATION
# ================================================================================

BASE_DIR   = (Path(__file__).resolve().parents[2] / "holdings")
PROC_DIR   = BASE_DIR / "processed"
OUTPUT_DIR = BASE_DIR / "results"
OUTPUT_DIR.mkdir(exist_ok=True)

# Set to False to run all 5 ETFs
VALIDATION_MODE = False

if VALIDATION_MODE:
    ETF_LIST = ["XME", "XLE"]
    print("Running in VALIDATION MODE: XME and XLE only.")
else:
    ETF_LIST = ["SPY", "XME", "XLE", "IHE", "XLV"]
    print("Running in FULL MODE: all 5 ETFs.")

# Sector benchmarks loaded from benchmark_mapping.csv (generated by 2d script).
# Mapping:
#   SPY -> ^GSPC      S&P 500 index (exact)
#   XME -> XLB        SPDR Materials ETF (XME is a metals/mining subset)
#   XLE -> ^GSPC      No sector index available on Yahoo; broad market fallback
#   IHE -> XLV        SPDR Health Care ETF (IHE is a pharma subset)
#   XLV -> ^SP500-35  S&P 500 Health Care index (exact)
#
# Fallback candidates used only if mapping file is missing.
ETF_BENCHMARK_CANDIDATES = {
    "SPY": ["^GSPC"],
    "XME": ["XLB", "^SP500-15", "^GSPC"],
    "XLE": ["^GSPC"],
    "IHE": ["XLV", "^SP500-35", "^GSPC"],
    "XLV": ["^SP500-35", "VHT", "^GSPC"],
}

# Market model parameters
ESTIMATION_WINDOW = 120   # trading days for OLS estimation
GAP               = 5     # days between estimation window end and event date
EVENT_H           = 3     # CAR window: [t0, t0 + EVENT_H]

# Shock detection threshold (standard deviations of stock's own CAR distribution)
SHOCK_THRESHOLD = 1.5

# Mechanism variable windows
ILLIQ_WINDOW      = 20
MISPRICING_WINDOW = 5

# ================================================================================
# STEP 0: LOAD DATA
# ================================================================================

print("\nLoading returns_clean.csv...")
_peek      = pd.read_csv(PROC_DIR / "returns_clean.csv", nrows=0)
_idx_col   = _peek.columns[0]
returns    = pd.read_csv(PROC_DIR / "returns_clean.csv",
                         index_col=_idx_col, parse_dates=True)
returns.index = pd.to_datetime(returns.index)
print(f"  Returns shape: {returns.shape}")

# Load benchmark prices (from 06_download_benchmarks.py)
print("Loading benchmarks.csv...")
_bpeak   = pd.read_csv(PROC_DIR / "benchmarks.csv", nrows=0)
_bidx    = _bpeak.columns[0]
benchmarks_df = pd.read_csv(PROC_DIR / "benchmarks.csv",
                             index_col=_bidx, parse_dates=True)
benchmarks_df.index = pd.to_datetime(benchmarks_df.index)
bench_returns = np.log(benchmarks_df / benchmarks_df.shift(1)).iloc[1:]
print(f"  Benchmark returns shape: {bench_returns.shape}")

# Load benchmark mapping (etf -> benchmark ticker)
mapping_path = PROC_DIR / "benchmark_mapping.csv"
if mapping_path.exists():
    _map_df       = pd.read_csv(mapping_path)
    ETF_BENCHMARK = dict(zip(_map_df["etf"], _map_df["benchmark"]))
    print(f"  Benchmark mapping: {ETF_BENCHMARK}")
else:
    ETF_BENCHMARK = {
        "SPY": "^GSPC", "XME": "XLB",
        "XLE": "^GSPC", "IHE": "XLV", "XLV": "^SP500-35",
    }
    print("  [WARN] benchmark_mapping.csv not found. Using hardcoded mapping.")

# Load GICS sector/industry classifications (from 08_download_gics.py)
gics_path = PROC_DIR / "gics_data.csv"
if gics_path.exists():
    gics_df = pd.read_csv(gics_path, index_col="ticker")
    print(f"  GICS data loaded: {len(gics_df)} tickers classified")
    print(f"  Unique sectors  : {gics_df['sector'].nunique()}")
    print(f"  Unique industries: {gics_df['industry'].nunique()}")
else:
    gics_df = pd.DataFrame(columns=["sector", "industry"])
    print("  [WARN] gics_data.csv not found. Similarity_ij will be binary (0/1).")

# Load Amihud illiquidity (from 10_download_volume.py)
amihud_path = PROC_DIR / "amihud.csv"
if amihud_path.exists():
    _apeak   = pd.read_csv(amihud_path, nrows=0)
    _aidx    = _apeak.columns[0]
    amihud_df = pd.read_csv(amihud_path, index_col=_aidx, parse_dates=True)
    amihud_df.index = pd.to_datetime(amihud_df.index)
    print(f"  Amihud data loaded: {amihud_df.shape}")
else:
    amihud_df = pd.DataFrame()
    print("  [WARN] amihud.csv not found. Falling back to volatility proxy.")


def load_holdings(etf: str) -> pd.DataFrame:
    df = pd.read_csv(PROC_DIR / f"{etf.lower()}_holdings.csv",
                     parse_dates=["atDate"])
    return df


def select_benchmark(etf: str) -> tuple:
    """
    Selects the benchmark for a given ETF.
    Looks first in bench_returns (dedicated benchmark data from benchmarks.csv),
    then falls back to the main returns matrix (returns_clean.csv).
    Returns (benchmark_ticker, benchmark_return_series).
    """
    ticker = ETF_BENCHMARK.get(etf)
    if ticker and ticker in bench_returns.columns:
        print(f"  Benchmark for {etf}: {ticker} (benchmarks.csv)")
        return ticker, bench_returns[ticker].dropna()
    candidates = ETF_BENCHMARK_CANDIDATES.get(etf, ["^GSPC"])
    for cand in candidates:
        if cand in returns.columns:
            print(f"  Benchmark for {etf}: {cand} (returns_clean.csv fallback)")
            return cand, returns[cand].dropna()
    if etf in returns.columns:
        print(f"  [WARN] {etf}: using ETF itself as benchmark (endogeneity risk)")
        return etf, returns[etf].dropna()
    raise ValueError(f"No benchmark found for {etf}")



# ================================================================================
# STEP 1: VECTORIZED SHOCK IDENTIFICATION
# ================================================================================

def identify_shocks_vectorized(ret_stocks: pd.DataFrame,
                                ret_bench:  pd.Series) -> pd.DataFrame:
    """
    Identifies shock events for all constituent stocks using vectorized
    numpy operations instead of a per-date Python loop.

    Strategy:
        For each stock i, construct two matrices aligned on the returns index:
          Y : (T x 1) stock returns
          X : (T x 2) [ones, benchmark returns]

        Then use a rolling window approach:
          - For each eligible event date t0, the estimation window is
            rows [t0 - WINDOW - GAP : t0 - GAP]
          - The event window is rows [t0 : t0 + EVENT_H]

        Instead of looping over dates, we use stride tricks to batch all
        windows into a 3D array and solve all OLS systems at once via
        numpy.linalg.lstsq on the batch.

    Returns DataFrame with columns: t0, stock_i, car_i, is_negative
    """
    # Align benchmark to stock index
    bench = ret_bench.reindex(ret_stocks.index).fillna(0).values  # (T,)
    dates = ret_stocks.index
    T     = len(dates)
    records = []

    # Pre-build X matrix (same for all stocks): [ones, bench]
    X_full = np.column_stack([np.ones(T), bench])  # (T, 2)

    # Minimum index for event date
    min_event_idx = ESTIMATION_WINDOW + GAP
    max_event_idx = T - EVENT_H - 1

    if min_event_idx >= max_event_idx:
        print("  [WARN] Not enough data for shock identification.")
        return pd.DataFrame()

    n_events = max_event_idx - min_event_idx
    print(f"  Eligible event dates: {n_events:,}")

    # Build estimation window indices for all event dates at once
    # est_start[k] = k,  est_end[k] = k + ESTIMATION_WINDOW
    # event_start[k] = k + ESTIMATION_WINDOW + GAP
    event_indices = np.arange(min_event_idx, max_event_idx)  # (n_events,)

    # Estimation window: [event_idx - ESTIMATION_WINDOW - GAP,
    #                     event_idx - GAP)
    est_starts = event_indices - ESTIMATION_WINDOW - GAP   # may be negative
    est_ends   = event_indices - GAP

    # Keep only events where estimation window is fully within data
    valid_mask  = est_starts >= 0
    event_indices = event_indices[valid_mask]
    est_starts    = est_starts[valid_mask]
    est_ends      = est_ends[valid_mask]
    n_valid       = len(event_indices)

    print(f"  Valid event dates (full estimation window): {n_valid:,}")

    n_stocks = ret_stocks.shape[1]

    for s_idx, ticker in enumerate(ret_stocks.columns):
        if s_idx % 10 == 0:
            print(f"    Processing stock {s_idx+1}/{n_stocks}: {ticker}")

        y_full = ret_stocks[ticker].fillna(0).values  # (T,)

        # --- Vectorized OLS for all event dates ---
        # Build batched estimation windows: shape (n_valid, ESTIMATION_WINDOW, 2)
        # and corresponding y: shape (n_valid, ESTIMATION_WINDOW)
        #
        # We use a strided approach: for each event k, extract rows
        # est_starts[k] : est_ends[k] from X_full and y_full

        alphas = np.full(n_valid, np.nan)
        betas  = np.full(n_valid, np.nan)

        # Batch OLS using stride tricks for speed
        # Build index arrays for all windows simultaneously
        idx_matrix = (est_starts[:, None] +
                      np.arange(ESTIMATION_WINDOW)[None, :])  # (n_valid, W)

        Y_batch = y_full[idx_matrix]          # (n_valid, W)
        X_batch = X_full[idx_matrix]          # (n_valid, W, 2)

        # Solve all OLS systems at once using einsum (normal equations)
        # For each k: beta = (X'X)^{-1} X'y
        XtX = np.einsum('kij,kil->kjl', X_batch, X_batch)  # (n_valid, 2, 2)
        Xty = np.einsum('kij,ki->kj',   X_batch, Y_batch)  # (n_valid, 2)

        # Solve batch of 2x2 systems
        det  = XtX[:, 0, 0] * XtX[:, 1, 1] - XtX[:, 0, 1] * XtX[:, 1, 0]
        safe = np.abs(det) > 1e-12

        alphas[safe] = (XtX[safe, 1, 1] * Xty[safe, 0]
                        - XtX[safe, 0, 1] * Xty[safe, 1]) / det[safe]
        betas[safe]  = (XtX[safe, 0, 0] * Xty[safe, 1]
                        - XtX[safe, 1, 0] * Xty[safe, 0]) / det[safe]

        # --- Vectorized CAR computation ---
        # Event window: rows [event_idx : event_idx + EVENT_H + 1]
        ev_idx_matrix = (event_indices[:, None] +
                         np.arange(EVENT_H + 1)[None, :])  # (n_valid, H+1)

        # Clip to valid range
        ev_idx_matrix = np.clip(ev_idx_matrix, 0, T - 1)

        R_event  = y_full[ev_idx_matrix]         # (n_valid, H+1)
        Rm_event = bench[ev_idx_matrix]           # (n_valid, H+1)

        # AR_t = R_t - alpha - beta * Rm_t
        AR = (R_event
              - alphas[:, None]
              - betas[:, None] * Rm_event)        # (n_valid, H+1)

        CARs = AR.sum(axis=1)                     # (n_valid,)

        # --- Flag shocks ---
        valid_cars = CARs[~np.isnan(alphas)]
        if len(valid_cars) < 10:
            continue

        car_mean = np.nanmean(valid_cars)
        car_std  = np.nanstd(valid_cars)
        if car_std < 1e-10:
            continue

        for k in range(n_valid):
            if np.isnan(alphas[k]) or np.isnan(CARs[k]):
                continue
            if abs(CARs[k] - car_mean) > SHOCK_THRESHOLD * car_std:
                records.append({
                    "t0":          dates[event_indices[k]],
                    "stock_i":     ticker,
                    "car_i":       CARs[k],
                    "is_negative": int(CARs[k] < 0),
                })

    return pd.DataFrame(records)


# ================================================================================
# STEP 2: MECHANISM VARIABLE UTILITIES
# ================================================================================

def illiquidity_proxy(ticker: str, t0: pd.Timestamp,
                       ret: pd.Series) -> float:
    """
    Amihud (2002) illiquidity ratio, computed as the rolling mean of
    |R_t| / (Volume_t * Price_t) over the pre-event window.

    If amihud_df is available (from 10_download_volume.py), uses the
    pre-computed rolling Amihud ratio. Otherwise falls back to rolling
    return volatility as a proxy.

    Higher value = less liquid = larger price impact per dollar traded.
    """
    if not amihud_df.empty and ticker in amihud_df.columns:
        past = amihud_df.index[amihud_df.index < t0]
        if len(past) > 0:
            val = amihud_df.loc[past[-1], ticker]
            if not np.isnan(val):
                return float(val)
    # Fallback: rolling return volatility
    past = ret.index[ret.index < t0]
    if len(past) < ILLIQ_WINDOW:
        return np.nan
    return float(ret.reindex(past[-ILLIQ_WINDOW:]).std())


def similarity(ticker_i: str, ticker_j: str) -> float:
    """
    GICS-based economic similarity between two stocks.

    Encoding:
        1.00  same industry   (narrow - likely informational spillover)
        0.50  same sector, different industry
        0.00  different sector (co-membership only, no informational link)

    Falls back to 1.0 (co-membership only) if GICS data is unavailable,
    which makes beta5 absorb a constant and not interpretable as spillover.
    """
    if gics_df.empty:
        return 1.0   # fallback: treat all co-members as equally similar

    row_i = gics_df.loc[ticker_i] if ticker_i in gics_df.index else None
    row_j = gics_df.loc[ticker_j] if ticker_j in gics_df.index else None

    if row_i is None or row_j is None:
        return 0.5   # unknown - assign middle value

    sector_i   = row_i.get("sector",   None)
    sector_j   = row_j.get("sector",   None)
    industry_i = row_i.get("industry", None)
    industry_j = row_j.get("industry", None)

    if pd.isna(sector_i) or pd.isna(sector_j):
        return 0.5   # missing sector - assign middle value

    if sector_i != sector_j:
        return 0.0   # different sector

    if pd.isna(industry_i) or pd.isna(industry_j):
        return 0.5   # same sector, unknown industry

    if industry_i == industry_j:
        return 1.0   # same industry

    return 0.5       # same sector, different industry


def mispricing_proxy(etf_ret: pd.Series,
                     bench_ret: pd.Series,
                     t0: pd.Timestamp) -> float:
    """
    ETF premium/discount proxy: cumulative ETF return minus benchmark
    over a short pre-event window.
    Replace with true (P_ETF - NAV)/NAV when NAV data is available.
    """
    past = etf_ret.index[etf_ret.index < t0]
    if len(past) < MISPRICING_WINDOW:
        return 0.0
    w = past[-MISPRICING_WINDOW:]
    return float(etf_ret.reindex(w).sum() - bench_ret.reindex(w).sum())


# ================================================================================
# STEP 3: BUILD OBSERVATION PANEL (j, e)
# ================================================================================

def compute_car_single(ret_stock: pd.Series,
                        ret_bench: pd.Series,
                        t0: pd.Timestamp) -> float:
    """
    Computes CAR for a single stock at a single event date.
    Used for receiver stocks j (less frequent than shock identification).
    """
    pre = ret_stock.index[ret_stock.index < t0]
    if len(pre) < ESTIMATION_WINDOW + GAP:
        return np.nan

    est_end   = pre[-(GAP + 1)]
    est_start = pre[-(ESTIMATION_WINDOW + GAP)]

    mask = (ret_stock.index >= est_start) & (ret_stock.index <= est_end)
    y    = ret_stock[mask].fillna(0).values
    x    = ret_bench.reindex(ret_stock[mask].index).fillna(0).values

    if len(y) < 30:
        return np.nan

    X = np.column_stack([np.ones(len(x)), x])
    try:
        coefs, *_ = np.linalg.lstsq(X, y, rcond=None)
    except Exception:
        return np.nan

    alpha, beta = coefs[0], coefs[1]

    future = ret_stock.index[ret_stock.index >= t0]
    if len(future) < EVENT_H + 1:
        return np.nan

    w_dates = future[:EVENT_H + 1]
    ar = (ret_stock.reindex(w_dates).fillna(0).values
          - alpha
          - beta * ret_bench.reindex(w_dates).fillna(0).values)
    return float(ar.sum())


def build_panel(shocks:      pd.DataFrame,
                holdings_df: pd.DataFrame,
                ret_stocks:  pd.DataFrame,
                ret_bench:   pd.Series,
                etf_ret:     pd.Series,
                etf_symbol:  str) -> pd.DataFrame:
    """
    Builds the observation panel (j, e) for the spillover regression.

    For each shock event (stock_i, t0), generates one row per co-constituent
    j != i with the dependent variable AR_j and all interaction terms.
    """
    rows = []
    hold_dates = sorted(holdings_df["atDate"].unique())
    n_shocks   = len(shocks)

    for evt_idx, (_, shock) in enumerate(shocks.iterrows()):
        if evt_idx % 500 == 0:
            print(f"    Building panel: event {evt_idx}/{n_shocks}...")

        t0      = shock["t0"]
        stock_i = shock["stock_i"]
        car_i   = shock["car_i"]
        is_neg  = shock["is_negative"]

        # Most recent holdings snapshot on or before t0
        past_hold = [d for d in hold_dates if d <= t0]
        if not past_hold:
            continue
        t_hold = past_hold[-1]
        hold_t = holdings_df[holdings_df["atDate"] == t_hold]

        # Weight of shocked stock i
        row_i = hold_t[hold_t["symbol"] == stock_i]
        if row_i.empty:
            continue
        w_i = float(row_i["weight"].iloc[0])
        if np.isnan(w_i) or w_i <= 0:
            continue

        # Mechanism variables at t0
        mispricing = mispricing_proxy(etf_ret, ret_bench, t0)

        # Co-constituents j != i
        peers = hold_t[hold_t["symbol"] != stock_i]["symbol"].tolist()

        for stock_j in peers:
            if stock_j not in ret_stocks.columns:
                continue

            r_j  = ret_stocks[stock_j]
            ar_j = compute_car_single(r_j, ret_bench, t0)
            if np.isnan(ar_j):
                continue

            illiq_j    = illiquidity_proxy(stock_j, t0, r_j)
            sim_ij     = similarity(stock_i, stock_j)
            illiq_safe = illiq_j if not np.isnan(illiq_j) else 0.0

            rows.append({
                "event_id":      f"{stock_i}_{t0.date()}",
                "etf":           etf_symbol,
                "stock_j":       stock_j,
                "stock_i":       stock_i,
                "t0":            t0,
                "AR_j":          ar_j,
                "Shock_i":       car_i,
                "w_i":           w_i,
                "Illiq_j":       illiq_j,
                "Mispricing_k":  mispricing,
                "Similarity_ij": sim_ij,
                "Neg_e":         is_neg,
                # Pre-computed interaction terms
                "b1_term":   car_i * w_i,
                "b2_term":   car_i * w_i * illiq_safe,
                "b4_term":   car_i * w_i * mispricing,
                "b5_term":   car_i * sim_ij,
                "asym_term": is_neg * car_i * w_i,
            })

    return pd.DataFrame(rows)


# ================================================================================
# STEP 4: SPILLOVER REGRESSION
# ================================================================================

def run_regression(panel: pd.DataFrame) -> None:
    """
    Estimates the core intra-ETF spillover regression with stock fixed effects
    and standard errors clustered by event_id.
    """
    required = ["AR_j", "b1_term", "b2_term", "b4_term", "b5_term", "asym_term"]
    df = panel.dropna(subset=required)

    if len(df) < 100:
        print(f"[WARN] Panel too small ({len(df)} obs). "
              f"Try lowering SHOCK_THRESHOLD.")
        return

    print(f"\nEstimating regression on {len(df):,} observations...")

    formula = ("AR_j ~ b1_term + b2_term + b4_term + b5_term + asym_term"
               " + C(stock_j)")

    result = smf.ols(formula, data=df).fit(
        cov_type="cluster",
        cov_kwds={"groups": df["event_id"]}
    )

    main_terms = ["b1_term", "b2_term", "b4_term", "b5_term", "asym_term"]

    print("\n" + "=" * 70)
    print("INTRA-ETF SPILLOVER REGRESSION RESULTS")
    print("=" * 70)
    tbl = result.summary2().tables[1]
    # Column names vary by statsmodels version - print all available columns
    available_cols = [c for c in ["Coef.", "Std.Err.", "t", "P>|t|",
                                   "z", "P>|z|", "[0.025", "0.975]"]
                      if c in tbl.columns]
    print(tbl.loc[main_terms, available_cols])
    print(f"\nN observations : {result.nobs:.0f}")
    print(f"Adjusted R-sq  : {result.rsquared_adj:.4f}")

    # Interpretation
    coefs  = result.params
    pvals  = result.pvalues
    labels = {
        "b1_term":   "beta1  Baseline propagation      (Shock x w_i)",
        "b2_term":   "beta2  Liquidity channel          (Shock x w_i x Illiq_j)",
        "b4_term":   "beta4  Arbitrage channel          (Shock x w_i x Mispricing)",
        "b5_term":   "beta5  Informational spillover    (Shock x Similarity)",
        "asym_term": "delta  Negative asymmetry         (Neg x Shock x w_i)",
    }
    print("\n-- Interpretation --")
    for term, label in labels.items():
        stars = ("***" if pvals[term] < 0.01 else
                 "**"  if pvals[term] < 0.05 else
                 "*"   if pvals[term] < 0.10 else "  ")
        print(f"  {label}: {coefs[term]:+.6f}  p={pvals[term]:.3f} {stars}")

    # Save text summary
    txt_path = OUTPUT_DIR / "regression_results.txt"
    with open(txt_path, "w") as f:
        f.write(result.summary().as_text())
    print(f"\nFull summary saved: {txt_path}")

    _plot_coefs(coefs, pvals, main_terms, labels)


def _plot_coefs(coefs, pvals, terms, labels):
    """Saves a coefficient plot."""
    fig, ax = plt.subplots(figsize=(8, 4))
    vals   = [coefs[t] for t in terms]
    short  = [labels[t].split()[0] for t in terms]
    colors = ["#E24B4A" if pvals[t] < 0.05 else "#888780" for t in terms]
    ax.barh(short, vals, color=colors, height=0.5)
    ax.axvline(0, color="#2C2C2A", linewidth=0.8, linestyle="--")
    ax.set_xlabel("Coefficient estimate")
    ax.set_title("Spillover regression coefficients  (red = p<0.05)",
                 fontsize=11)
    plt.tight_layout()
    out = OUTPUT_DIR / "coef_plot.png"
    plt.savefig(out, dpi=150)
    plt.close()
    print(f"Coefficient plot saved: {out}")


def asymmetry_analysis(panel: pd.DataFrame) -> None:
    """Estimates the model separately for positive and negative shocks (H5)."""
    for sign, label in [(0, "POSITIVE"), (1, "NEGATIVE")]:
        sub = panel[panel["Neg_e"] == sign].dropna(
            subset=["AR_j", "b1_term", "b2_term", "b4_term", "b5_term"])
        if len(sub) < 50:
            print(f"[WARN] Too few {label} shocks ({len(sub)}). Skipping.")
            continue
        formula = "AR_j ~ b1_term + b2_term + b4_term + b5_term + C(stock_j)"
        res = smf.ols(formula, data=sub).fit(
            cov_type="cluster",
            cov_kwds={"groups": sub["event_id"]})
        print(f"\n{'=' * 60}")
        print(f"SUBSAMPLE: {label} SHOCKS  (N={res.nobs:.0f})")
        print(f"{'=' * 60}")
        tbl = res.summary2().tables[1]
        available_cols = [c for c in ["Coef.", "Std.Err.", "t", "P>|t|",
                                       "z", "P>|z|"]
                          if c in tbl.columns]
        print(tbl.loc[["b1_term","b2_term","b4_term","b5_term"],
                       available_cols])


# ================================================================================
# MAIN
# ================================================================================

if __name__ == "__main__":

    # If panel_full.csv already exists, skip shock identification and
    # load directly to save time. Delete the file to rerun from scratch.
    panel_path = OUTPUT_DIR / "panel_full.csv"
    if panel_path.exists():
        print("")
        print(f"Loading existing panel from {panel_path}...")
        full_panel = pd.read_csv(panel_path, parse_dates=["t0"])
        print(f"  Panel shape: {full_panel.shape}")
        run_regression(full_panel)
        asymmetry_analysis(full_panel)
        import sys; sys.exit(0)

    panels_all = []

    for etf in ETF_LIST:
        print(f"\n{'=' * 60}")
        print(f"ETF: {etf}")
        print(f"{'=' * 60}")

        hold_df = load_holdings(etf)

        # Select sector benchmark (external to the ETF)
        try:
            bench_sym, ret_bench = select_benchmark(etf)
        except ValueError as e:
            print(f"  [ERROR] {e}. Skipping {etf}.")
            continue

        etf_ret = returns[etf].dropna() if etf in returns.columns else ret_bench

        # Constituent stocks with available returns
        etf_stocks   = hold_df["symbol"].unique().tolist()
        avail_stocks = [t for t in etf_stocks if t in returns.columns
                        and t != bench_sym]  # exclude benchmark from constituents
        ret_stocks   = returns[avail_stocks]

        print(f"  Holdings symbols    : {len(etf_stocks):,}")
        print(f"  With return data    : {len(avail_stocks):,}")

        if len(avail_stocks) < 5:
            print(f"  [WARN] Too few stocks. Skipping {etf}.")
            continue

        # Identify shocks (vectorized)
        print(f"\n  Identifying shocks "
              f"(threshold={SHOCK_THRESHOLD}sigma, vectorized)...")
        shocks = identify_shocks_vectorized(ret_stocks, ret_bench)
        print(f"  Shocks identified: {len(shocks):,}")

        if shocks.empty:
            print(f"  [WARN] No shocks found. Try lowering SHOCK_THRESHOLD.")
            continue

        # Shock statistics
        n_neg = shocks["is_negative"].sum()
        n_pos = len(shocks) - n_neg
        print(f"  Positive shocks: {n_pos:,}  |  Negative shocks: {n_neg:,}")

        # Build panel
        print(f"\n  Building observation panel (j, e)...")
        panel = build_panel(shocks, hold_df, ret_stocks,
                            ret_bench, etf_ret, etf)
        print(f"  Panel observations: {len(panel):,}")

        if not panel.empty:
            panels_all.append(panel)

    if not panels_all:
        print("\n[ERROR] No panels built. Check data and configuration.")
    else:
        full_panel = pd.concat(panels_all, ignore_index=True)
        print(f"\nFull panel: {len(full_panel):,} observations")

        panel_path = OUTPUT_DIR / "panel_full.csv"
        full_panel.to_csv(panel_path, index=False)
        print(f"Panel saved: {panel_path}")

        run_regression(full_panel)
        asymmetry_analysis(full_panel)



